# Generated by Django 4.0.4 on 2022-06-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='autor',
            field=models.CharField(max_length=100),
        ),
    ]
